Stour/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path,include


urlpatterns = [
    path('', include('apps.usuarios.urls')),
    #path('lugares/', include('apps.lugares.urls')),
    #path('misiones/', include('apps.misiones.urls')),
    #path('premios/', include('apps.premios.urls')),
    path('admin/', admin.site.urls),
    
   
]

apps/lugares/models.py
from django.db import models
from apps.usuarios.models import Usuarios

class Lugares(models.Model):
    id_lugar = models.AutoField(primary_key=True)
    nombre_lugar = models.CharField(max_length=50)
    rut_usuario = models.ForeignKey(Usuarios,on_delete=models.CASCADE,null=True) 
    estado_lugar = models.CharField(max_length=100,default='Pendiente')
    imagen_lugar = models.ImageField(upload_to='apps/lugares/static/lugares/lugares',default='image.png')

apps/lugares/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    
    image = forms.ImageField()

apps/lugares/views.py
from django.shortcuts import render
from apps.lugares.forms import ImageUploadForm
from django.http import HttpResponseForbidden
from django.http import HttpResponse
from apps.lugares.models import Lugares

def LugaresView(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            idlugar = request.POST.get('idlugar')
            m = Lugares.objects.get(id_lugar=idlugar)
            m.imagen_lugar = form.cleaned_data['image']
            m.estado_lugar = "En Proceso"
            m.save()
            errors = 'Imagen Enviada con Exito'
            context = {
                
                'errors': errors
            }
            return render(request, 'lugares/lugarespendientes.html', context)
        else:
            errors = 'Imagen No Valida'
            context = {
                
                'errors': errors
            }
        return render(request, 'lugares/lugarespendientes.html', context)

apps/lugares/templates/lugares/lugarespendientes.html
{% extends 'usuarios/plantilla.html' %}

{% load static %}

{% block lugarespendientes %}
{% block contenido %}
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Inicio</a></li>
        <li class="breadcrumb-item active">Lugares Pendientes</li>
      </ul>
    </div>
  </div>
  <section>
    <div class="container-fluid">
      <!-- Page Header-->
      <header> 
        <h1 class="h3 display">Lugares Pendientes</h1>
      </header>
      {% if errors %}
        <p>{{ errors }}</p>
      {% endif %}
      <div class="row">
        <div class="col-xs-12 col-md-12">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>Estrellas</th>
                      <th>Descripcion</th>
                      <th>Foto</th>
                      <th>Estado Visita</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for a in datos4 %}  
                    <tr>
                      <th scope="row">1<img src="{% static 'usuarios/img/estrella.jpg' %}" alt="estrella" height="30px"></th>
                      <td>{{ a.nombre_lugar }}</td>
                      <td>
                          <form action="{% url 'lugarespendientes2' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                            <p>
                                <input id="id_image" type="file" class="" name="image">
                                <input type="hidden" value="{{ a.id_lugar }}" name="idlugar">
                            </p>
                            <input type="submit" value="Enviar Foto" />
                        </form>
                      </td>
                      <td>{{ a.estado_lugar }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock contenido %}
{% endblock lugarespendientes %}

apps/lugares/templates/lugares/lugaresrecorridos.html
{% extends 'usuarios/plantilla.html' %}

{% load static %}

{% block lugaresrecorridos %}
      <!-- Breadcrumb-->
      <div class="breadcrumb-holder">
        <div class="container-fluid">
          <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Inicio</a></li>
            <li class="breadcrumb-item">Lugares</li>
          </ul>
        </div>
      </div>
      <section class="charts">
        <div class="container-fluid">
          <!-- Page Header-->
          <header> 
              <h1 class="h3 display">Lugares Recorridos</h1>
          </header>
          <div class="col-lg-12 col-md-12">
            <!--Lugares Recorridos-->
      </section>
{% endblock lugaresrecorridos %}      
     